# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-06 09:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shiptrader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listed_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 9, 29, 21, 553565, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='starship',
            name='cargo_capacity',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='starship',
            name='crew',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='starship',
            name='hyperdrive_rating',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='starship',
            name='length',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='starship',
            name='passengers',
            field=models.CharField(max_length=20),
        ),
    ]
